### ISSUE TITLE
Not allow identities

### ISSUE THREAD

**Issue by programacion-web** [RainLoop/rainloop-webmail#667]
Hello friends,

Thanks for the great rainloop development.

I would like to disallow Ami identities or accounts extras like I can disable this option.

I want to disable all menu settings "accounts"

thanks

**Comment by RainLoop** [comment]
OK

![image](https://cloud.githubusercontent.com/assets/5530092/7671864/fa2d0c1a-fce7-11e4-9ebd-4557173391a2.png)

**Comment by RainLoop** [comment]
Done (1.9.1 version)

**Comment by programacion-web** [comment]
I have 1.9.1 version, and I still appears, the menu accounts.

How I can do to disable this option?

![screenshot_2015-05-18_16-24-28](https://cloud.githubusercontent.com/assets/7329190/7692964/dd3bcfb2-fd8f-11e4-88bb-c0ca9870fca9.png)

thanks

**Comment by megadr01d** [comment]
Login into the admin area (append `?admin` to your Rainloop URL) and disable the creation of additional accounts/identities in the **General** tab.
